### PR TITLE
Greatly decrease build time for large vocabs

### PR DESCRIPTION
**Pull request by literarymachine**

### CODE REVIEW

**Comment by acka47** [comment]
I just tried to test it locally. After having the usual problems with npm, node etc. and updating to newer stable versions, I didn't make it anyway to start the dev system. I always get – in this branch and the master branch – the following:

```
Encountered an error parsing the provided GraphQL type definitions:
Syntax Error: Expected Name, found }

  24 |     inbox: String
  25 |   }
  26 |
  27 |   type LanguageMap {
  28 |
> 29 |   }
     |   ^
  30 |   type LanguageMapArray {
  31 |
  32 |   }
  33 |

```

**Comment by literarymachine** [comment]
> I just tried to test it locally. After having the usual problems with npm, node etc. and updating to newer stable versions

I am not entirely sure, but I think this is a problem that is supposed to be fixed in d376fc3112a6a8543e37bb59603b1ec9ff87edf2. Can you `rm -r node_modules` and `npm i` again? Also, maybe @dr0i can take a look on you machine.

**Comment by dr0i** [comment]
@acka47 :  `npm  run build' is fine here ( doing 'npm test' I got a different error concerning Webhooks which is most likely because of some config issue and not an issue here).

To be on the safe side, create a new directory, freshly clone the repo into that. Then:
$ nvm install 12.16.0; nvm use 12.16.0; cp .env.example .env;  cp test/data/systematik.ttl data/; npm install; npm run build
 
Then look into the `public` directory to find your vocabulary.

**Comment by acka47** [comment]
Thanks @dr0i , I got it running following your guide. +1

**Comment by dr0i** [comment]
Deployed, closed.

**Pull request merged**
