### PR TITLE
Make links more visible

### PR DESCRIPTION
**Pull request by dobladov**
Fixes: https://github.com/hbz/skohub-vocabs/issues/57
localhost_8000_w3id org_class_hochschulfaecher_S17 html

### CODE REVIEW

**Comment by literarymachine** [comment]
I think @acka47 was referring to the links in the description of e.g. https://skohub.io/dini-ag-kim/hochschulfaechersystematik/w3id.org/class/hochschulfaechersystematik/scheme.html

@acka47 or did you also want the links in the tree reformatted?

**Comment by acka47** [comment]
Yes, I was talking about links in running text. I don't think they need to look like this in the tree.

**Comment by dobladov** [comment]
I made only the content links more visible.
localhost_8000_w3id org_class_hochschulfaecher_F17 html

**Comment by acka47** [comment]
That looks good. +1

**Pull request merged**
