### PR TITLE
display altLabels, support for displaying multiple altLabels

### PR DESCRIPTION
**Pull request by sroertgen**
Hello there,

we (big help of @torsten-simon) added the display of multiple altLabels in the json-output. Before altLabels were not displayed.

### CODE REVIEW

**Comment by acka47** [comment]
@dr0i Please deploy on test for functional review.

**Comment by dr0i** [comment]
Deployed to test, see e.g. https://test.skohub.io/dr0i/skos/heads/master/page-data/onto.tib.eu/destf/cs/1576.html/page-data.json.
Code looks also good.
What do you think, @acka47 ?

**Comment by dr0i** [comment]
deployed to test

**Comment by dr0i** [comment]
Deployed to production.
Note that `altLabels` only exist in `skohub.io` for vocabs deployed _after_ this PR.

**Pull request merged**
