### PR TITLE
Add "inbox" and "followers" to JSON-LD context

### PR DESCRIPTION
**Pull request by acka47**
Fixes https://github.com/hbz/skohub-vocabs/issues/87

### CODE REVIEW

**Comment by acka47** [comment]
I think there is something wring with the test infrastructure. All tests fail to run with this message:

>  Test suite failed to run
>
>    [BABEL] /home/runner/work/skohub-vocabs/skohub-vocabs/test/{test}.test.js: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'

 Please help, @literarymachine .

**Comment by dr0i** [comment]
I think we can fix it leaving @literarymachine in parental leave ...
To begin with, it `npm test` works on our machines even using your branch (one must stop the `skohub-vocabs` daemon, though, for the test instance uses the same port when testing `webHookServer`. TODO: document this).
Second, e.g. `laravel` needs a newer babel/preset-env lib ,which may be installed on the github test environment. We use <v7.9.

**Comment by dr0i** [comment]
@acka47 as the last commit fixed the github test - ping if this PR ready to be merged and deployed.

**Comment by acka47** [comment]
+1 Please merge and deploy

**Comment by dr0i** [comment]
Merged and deployed, but see #87 for further questions.

**Pull request merged**
